import type { StrategyDefinition, RuleDef, IndicatorType } from "@algo-farm/shared/strategy";

export type CommentFormat = "cs" | "pine";

// ---------------------------------------------------------------------------
// Human-readable labels for indicator types
// ---------------------------------------------------------------------------

const IND_LABELS: Partial<Record<IndicatorType, string>> = {
  sma: "SMA",
  ema: "EMA",
  rsi: "RSI",
  macd: "MACD",
  atr: "ATR",
  atr_robust: "ATR (Robust)",
  atr_gaussian: "ATR (Gaussian)",
  adx: "ADX",
  cci: "CCI",
  stoch: "Stochastic",
  bollinger_bands: "Bollinger Bands",
  bollinger_upper: "Bollinger Upper Band",
  bollinger_lower: "Bollinger Lower Band",
  bollinger_basis: "Bollinger Basis",
  supertrend: "SuperTrend",
  supertrend_direction: "SuperTrend Direction",
  vwap: "VWAP",
  vwap_upper: "VWAP Upper Band",
  vwap_lower: "VWAP Lower Band",
  anchored_vwap: "Anchored VWAP",
  anchored_vwap_upper: "Anchored VWAP Upper",
  anchored_vwap_lower: "Anchored VWAP Lower",
  session_active: "Session Active",
  session_high: "Session High",
  session_low: "Session Low",
  range_fakeout_short: "Range Fakeout (Short)",
  range_fakeout_long: "Range Fakeout (Long)",
  momentum: "Momentum",
  roc: "Rate of Change",
  volume_sma: "Volume SMA",
  htf_ema: "Higher-TF EMA",
  htf_sma: "Higher-TF SMA",
  obv: "OBV",
  williamsr: "Williams %R",
  close: "Close Price",
  open: "Open Price",
  high: "High Price",
  low: "Low Price",
  volume: "Volume",
};

// ---------------------------------------------------------------------------
// Rule translation
// ---------------------------------------------------------------------------

function ruleText(rule: RuleDef): string {
  const lhs = rule.indicator;
  const rhs = rule.compare_to != null ? rule.compare_to : String(rule.value ?? 0);

  switch (rule.condition) {
    case ">":           return `${lhs} > ${rhs}`;
    case "<":           return `${lhs} < ${rhs}`;
    case ">=":          return `${lhs} >= ${rhs}`;
    case "<=":          return `${lhs} <= ${rhs}`;
    case "crosses_above": return `${lhs} crosses above ${rhs}`;
    case "crosses_below": return `${lhs} crosses below ${rhs}`;
    default:            return `${lhs} ${rule.condition} ${rhs}`;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a human-readable header comment describing the strategy's
 * working principles (indicators, entry/exit logic, risk management).
 *
 * For 'cs': returns a C# XML /// <summary> block (without trailing newline).
 * For 'pine': returns a line-comment block starting with // === (without trailing newline).
 */
export function generateStrategyPrinciples(
  strategy: StrategyDefinition,
  format: CommentFormat,
): string {
  const date = new Date().toISOString().slice(0, 10);

  const body: string[] = [];
  body.push(`Strategy: ${strategy.name} (${strategy.variant}) — Generated by AlgoFarm ${date}`);
  body.push("");

  // Indicators
  body.push("INDICATORS");
  for (const ind of strategy.indicators) {
    const label = IND_LABELS[ind.type as IndicatorType] ?? ind.type;
    const paramStr = Object.entries(ind.params)
      .filter(([, v]) => typeof v === "number" || typeof v === "string")
      .map(([k, v]) => `${k}=${v}`)
      .join(", ");
    body.push(`  - ${label} (${ind.name})${paramStr ? `: ${paramStr}` : ""}`);
  }
  body.push("");

  // Entry long
  if (strategy.entry_rules.length > 0) {
    body.push("ENTRY LOGIC (LONG)");
    for (const r of strategy.entry_rules) body.push(`  - ${ruleText(r)}`);
    body.push("");
  }

  // Exit long
  if (strategy.exit_rules.length > 0) {
    body.push("EXIT LOGIC (LONG)");
    for (const r of strategy.exit_rules) body.push(`  - ${ruleText(r)}`);
    body.push("");
  }

  // Short rules
  const shortEntry = strategy.entry_rules_short ?? [];
  const shortExit = strategy.exit_rules_short ?? [];
  if (shortEntry.length > 0) {
    body.push("ENTRY LOGIC (SHORT)");
    for (const r of shortEntry) body.push(`  - ${ruleText(r)}`);
    body.push("");
  }
  if (shortExit.length > 0) {
    body.push("EXIT LOGIC (SHORT)");
    for (const r of shortExit) body.push(`  - ${ruleText(r)}`);
    body.push("");
  }

  // Risk management
  const pm = strategy.position_management;
  body.push("RISK MANAGEMENT");
  const riskPct =
    pm.risk_pct != null ? pm.risk_pct * 100 : (pm.size ?? 0.02) * 100;
  body.push(`  - Risk per trade: ${riskPct.toFixed(1)}%`);
  if (pm.sl_pips != null)       body.push(`  - Fixed SL: ${pm.sl_pips} pips`);
  if (pm.tp_pips != null)       body.push(`  - Fixed TP: ${pm.tp_pips} pips`);
  if (pm.sl_atr_mult != null)   body.push(`  - ATR-based SL: ${pm.sl_atr_mult}\u00d7ATR`);
  if (pm.tp_atr_mult != null)   body.push(`  - ATR-based TP: ${pm.tp_atr_mult}\u00d7ATR`);
  if (pm.trailing_sl)           body.push(`  - Trailing SL: ${pm.trailing_sl}`);
  if (pm.scale_out)             body.push(`  - Scale-out: ${pm.scale_out.volume_pct}% at ${pm.scale_out.trigger_r}R`);
  if (pm.time_exit_bars)        body.push(`  - Time exit: close after ${pm.time_exit_bars} bars in loss`);
  body.push("");
  body.push("WARNING: Review and test thoroughly before live trading");

  if (format === "cs") {
    return [
      "/// <summary>",
      ...body.map((l) => `/// ${l}`.trimEnd()),
      "/// </summary>",
    ].join("\n");
  } else {
    const sep = "// " + "=".repeat(60);
    return [
      sep,
      ...body.map((l) => `// ${l}`.trimEnd()),
      sep,
    ].join("\n");
  }
}
